id: P004589
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20492
  title: དཔྱོད་མིག་།
  author: ''
  volumes:
    b1375ab1becd405bb023d50f5b14f0f8:
      image_group_id: I8LS20494
      title: ''
      volume_number: 1
      total_pages: 352
      base_file: v001.txt
